---
title: "A natureza da econometria"
crossref:
  eq-prefix: Equação
---

## Análises econômicas

Um modelo econômico consiste em equações matemáticas que descrevem várias relações. Um exemplo é o modelo econômico do crime:

$$y = f(x_1, x_2, x_3, x_4)$$

em que:

$x_1$ = horas gastas em atividades criminosas\
$x_2$ = "salário" por hora em atividade criminosa\
$x_3$ = salário por hora em emprego legal\
$x_4$ = probabilidade de ser capturado\

Um modelo econômico pode ser escrito como uma função mais geral $f(.)$.

A partir de um modelo econômico, podemos especificar o **modelo econométrico** a partir dos dados disponíveis. $$crime = \beta_0 + \beta_{1}wage_m + \beta_{2}otherinc + \beta_{3}freqarr + \mu$$ Com a definição dos modelos econométricos, poderíamos levantar a hipótese de que $\beta_2 = 0$. A análise empírica, por definição, requer dados.

## Estrutura dos dados econômicos

### Corte transversal (*cross-section*)

Consiste em uma amostra de indivíduos em determinado ponto no tempo.

### Séries temporais

Observações de uma ou várias variáveis ao longo do tempo. Diferentemente do corte transversal, os dados de séries temporiai frequentemente têm influência dos valores passados. Também é preciso ficar atento à sazonalidade.

### Cortes transversais agrupados

O conjunto de dados tem característica tanto de corte transversal quanto de séries temporais. Muito usado para analisar os efeitos de uma política de governo. Por exemplo, são coletados dados anteriores e posteriores a uma política pública.

### Dados de painel

Diferentemente dos dados de corte transversal agrupado, os dados de painel se referem ao *mesmo* indivíduo ao longo do tempo. Possui a vantagem de podermos controlar para fatores não observáveis.

## Causalidade e *ceteris paribus*

A noção de "todos os outros fatores constantes" desempenha função importante para estabelecer causalidade.
