project:
  type: book
  output-dir: docs
  
book:
  title: "Resumo - Econometria"
  author: "Bruno Veloni"
  date: "12/25/2022"
  language: "pt-BR"
  chapters:
    - index.qmd
    - summary.qmd
    - 01_cap1.qmd
    - 02_cap2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: journal
  pdf:
    documentclass: scrreprt

editor: visual

